// Question 23: Conditional Tests: Write a series of conditional tests. Print a statement 
// describing each test and your prediction for the results of each test.
var myName = "Ali";
console.log("Is myName == 'Ali'? I predict true");
console.log(myName == 'Ali');
var myAge = 16;
console.log("Is myAge == '14'? I predict false");
console.log(myAge == 14);
var myGender = "Male";
console.log("Is myGender == 'Male'? I predict true");
console.log(myGender == 'Male');
var myNationality = "Pakistani";
console.log("Is myNationality == 'Dutch'? I predict false");
console.log(myNationality == 'Dutch');
var myReligion = "Islam";
console.log("Is myReligion == 'Islam'? I predict True");
console.log(myReligion == 'Islam');
var myWeight = 62;
console.log("Is myWeight == '50'? I predict false");
console.log(myWeight == 50);
var myHeight = "5'11";
console.log("Is myHeight == '5'11'? I predict True");
console.log(myHeight == "5'11");
var myHobby = "Gaming";
console.log("Is myHobby == 'Sports'? I predict false");
console.log(myHobby == 'Sports');
var mySkinColor = "Brown";
console.log("Is mySkinColor == 'Brown'? I predict true");
console.log(mySkinColor == 'Brown');
var myLanguage = "Urdu";
console.log("Is myLanguage == 'German'? I predict false");
console.log(myLanguage == 'German');
